# Generated by Django 5.2.9 on 2025-12-15 08:25

import django.db.models.deletion
from django.db import migrations, models


def cleanup_invalid_data(apps, schema_editor):
    """Delete messages and groups with invalid foreign keys before schema changes"""
    Message = apps.get_model('Chat', 'Message')
    Group = apps.get_model('Chat', 'Group')
    # Delete all messages and groups to avoid foreign key constraint issues
    # Since this is development, this is safe
    Message.objects.all().delete()
    Group.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0001_initial'),
    ]

    operations = [
        # Clean up invalid data before schema changes
        migrations.RunPython(cleanup_invalid_data, migrations.RunPython.noop),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profile_photos/')),
            ],
        ),
        migrations.AlterModelOptions(
            name='message',
            options={},
        ),
        migrations.AddField(
            model_name='message',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='message_attachments/'),
        ),
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(related_name='groups', to='Chat.user'),
        ),
        migrations.AlterField(
            model_name='group',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_groups', to='Chat.user'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='Chat.user'),
        ),
        migrations.AlterField(
            model_name='message',
            name='to_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='Chat.user'),
        ),
    ]
